export const listQuestions = [
  {
    version: '1.0',
    createdDate: 1690661222806,
    lastModifiedDate: 1690661222806,
    deleted: false,
    id: '64c57166220fb8269b7d07c0',
    question: {
      sound: '/data/sounds/Test2_1.mp3',
      text: '',
      hint: '',
      image: '/data/images/Test2_1.png',
    },
    answer: {
      choices: ['"(B)"', '"(C)"', '"(D)"'],
      hint: '<b>Transcript:</b> <br> <br> <b> (A) The plane is docked at the airport. </b><br>(B) There is luggage being put onto the plane. <br>(C) There are many people boarding the plane. <br>(D) There are maintenance workers fixing the plane.',
      image: '',
      texts: ['(A)'],
    },
    topicId: '64bfdda4eadd9108158c40f2',
    childCards: [
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
      },
    ],
    examId: '64c409c3861e6a27b44a0bf8',
  },
  {
    version: '1.0',
    createdDate: 1690661222809,
    lastModifiedDate: 1690661222809,
    deleted: false,
    id: '64c57166220fb8269b7d07c1',
    question: {
      sound: '/data/sounds/Test2_2.mp3',
      text: '',
      hint: '',
      image: '/data/images/Test2_2.png',
    },
    answer: {
      choices: ['"(B)"', '"(C)"', '"(D)"'],
      hint: '<b>Transcript:</b> <br><b>  (A) The woman is drinking a cup of coffee</b><br>(B) The woman is listening to music. <br>(C) The woman is talking on her cell phone. <br>(D) The woman is looking at the newspaper.',
      image: '',
      texts: ['(A)'],
    },
    topicId: '64bfdda4eadd9108158c40f2',
    childCards: [
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
      },
    ],
    examId: '64c409c3861e6a27b44a0bf8',
  },
  {
    version: '1.0',
    createdDate: 1690661222812,
    lastModifiedDate: 1690661222812,
    deleted: false,
    id: '64c57166220fb8269b7d07c2',
    question: {
      sound: '/data/sounds/Test2_3.mp3',
      text: '',
      hint: '',
      image: '/data/images/Test2_3.png',
    },
    answer: {
      choices: ['"(A)"', '"(C)"', '"(D)"'],
      hint: '<b>Transcript:</b> <br> (A)She is fixing the wheel on her bike. <br><b> (B) She is changing the tire on her car. </b><br>(C) She is putting oil into her car. <br>(D) She is standing behind the windmill.',
      image: '',
      texts: ['(B)'],
    },
    topicId: '64bfdda4eadd9108158c40f2',
    childCards: [
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
      },
    ],
    examId: '64c409c3861e6a27b44a0bf8',
  },
  {
    version: '1.0',
    createdDate: 1690661222815,
    lastModifiedDate: 1690661222815,
    deleted: false,
    id: '64c57166220fb8269b7d07c3',
    question: {
      sound: '/data/sounds/Test2_4.mp3',
      text: '',
      hint: '',
      image: '/data/images/Test2_4.png',
    },
    answer: {
      choices: ['"(A)"', '"(B)"', '"(D)"'],
      hint: '<b>Transcript:</b> <br> (A)They are very close to the chairlift. <br>(B) They are making snow. <br><b> (C) The people are skiing down the mountain. </b><br>(D) All of the skiers are wearing helmets.',
      image: '',
      texts: ['(C)'],
    },
    topicId: '64bfdda4eadd9108158c40f2',
    childCards: [
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
      },
    ],
    examId: '64c409c3861e6a27b44a0bf8',
  },
  {
    version: '1.0',
    createdDate: 1690661222819,
    lastModifiedDate: 1690661222819,
    deleted: false,
    id: '64c57166220fb8269b7d07c4',
    question: {
      sound: '/data/sounds/Test2_5.mp3',
      text: '',
      hint: '',
      image: '/data/images/Test2_5.png',
    },
    answer: {
      choices: ['"(A)"', '"(B)"', '"(C)"'],
      hint: '<b>Transcript:</b> <br> (A)The people are drinking glasses of juice. <br>(B) She is giving a presentation about September’s sales figures. <br> (C) All of the women are sitting down. <br> <b>  (D) One of the women is giving a business presentation on a whiteboard. </b>',
      image: '',
      texts: ['(D)'],
    },
    topicId: '64bfdda4eadd9108158c40f2',
    childCards: [
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
      },
    ],
    examId: '64c409c3861e6a27b44a0bf8',
  },
  {
    version: '1.0',
    createdDate: 1690661222821,
    lastModifiedDate: 1690661222821,
    deleted: false,
    id: '64c57166220fb8269b7d07c5',
    question: {
      sound: '/data/sounds/Test2_6.mp3',
      text: '',
      hint: '',
      image: '/data/images/Test2_6.png',
    },
    answer: {
      choices: ['(A)', '(C)', '(D)'],
      hint: '<b>Transcript:</b> <br> (A)The men are adjusting headsets. <br><b> (B) The women are wearing headsets. </b>  <br>(C) The men are using a mouse with the laptop. <br>(D) The women are talking to each other.',
      image: '',
      texts: ['(B)'],
    },
    topicId: '64bfdda4eadd9108158c40f2',
    childCards: [
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
        answer: {
          choices: [],
          hint: '',
          image: '',
          texts: [],
        },
      },
      {
        version: '1.0',
        deleted: false,
        question: {
          sound: '',
          text: '',
          hint: '',
          image: '',
        },
      },
    ],
    examId: '64c409c3861e6a27b44a0bf8',
  },
];
